[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "clamSearch"
authors = [
    {name = "Will Koester", email = "wikoeste@cisco.com"}
]
description = "Clam AV Sig Search & Drop Tool"
version = "0.1"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "requests",
    "os",
    "sys",
    "re",
    "getpass",
    "json",
    "terminaltables"
]

[project.scripts]
clam = "main:main"
